const fs = require('fs');
const path = require('path');

function generateSDK(config, outputPath) {
  const features = config.features || {};
  const baseUrl = `http://localhost:${config.project.port || 3001}`;
  const wsEnabled = config.websocket?.enabled;

  const lines = [
    `// skeletal-client.js — auto-generated by skeletal-dock`,
    `// Project: ${config.project.name}`,
    ``,
    `const SKELETAL_BASE = '${baseUrl}/api';`,
    ``,
    `async function _req(method, path, body, token) {`,
    `  const headers = { 'Content-Type': 'application/json' };`,
    `  if (token) headers['Authorization'] = 'Bearer ' + token;`,
    `  const res = await fetch(SKELETAL_BASE + path, {`,
    `    method,`,
    `    headers,`,
    `    body: body ? JSON.stringify(body) : undefined`,
    `  });`,
    `  const json = await res.json();`,
    `  if (!res.ok) throw Object.assign(new Error(json.error || 'Request failed'), { status: res.status, data: json });`,
    `  return json;`,
    `}`,
    ``
  ];

  if (features.auth?.enabled) {
    lines.push(
      `// --- Auth ---`,
      `const skeletalAuth = {`,
      `  register: (email, password, name) => _req('POST', '/auth/register', { email, password, name }),`,
      `  login: (email, password) => _req('POST', '/auth/login', { email, password }),`,
      `  logout: (refreshToken) => _req('POST', '/auth/logout', { refreshToken }),`,
      `  refresh: (refreshToken) => _req('POST', '/auth/refresh', { refreshToken }),`,
      `  me: (token) => _req('GET', '/auth/me', null, token),`,
      `};`,
      ``
    );
  }

  if (features.otp?.enabled) {
    lines.push(
      `// --- OTP ---`,
      `const skeletalOTP = {`,
      `  send: (target, type, purpose) => _req('POST', '/otp/send', { target, type, purpose }),`,
      `  verify: (target, code, type, purpose) => _req('POST', '/otp/verify', { target, code, type, purpose }),`,
      `};`,
      ``
    );
  }

  if (features.webhooks?.enabled) {
    lines.push(
      `// --- Webhooks ---`,
      `const skeletalWebhooks = {`,
      `  register: (url, events, label) => _req('POST', '/webhooks/register', { url, events, label }),`,
      `  list: () => _req('GET', '/webhooks'),`,
      `  remove: (id) => _req('DELETE', '/webhooks/' + id),`,
      `  trigger: (event, data, token) => _req('POST', '/webhooks/trigger', { event, data }, token),`,
      `};`,
      ``
    );
  }

  if (features.crud?.enabled && Array.isArray(features.crud.models)) {
    features.crud.models.forEach(model => {
      const name = model.name.toLowerCase();
      const varName = `skeletal${model.name.charAt(0).toUpperCase() + model.name.slice(1)}`;
      lines.push(
        `// --- CRUD: ${model.name} ---`,
        `const ${varName} = {`,
        `  list: (params, token) => _req('GET', '/${name}?' + new URLSearchParams(params || {}), null, token),`,
        `  get: (id, token) => _req('GET', '/${name}/' + id, null, token),`,
        `  create: (data, token) => _req('POST', '/${name}', data, token),`,
        `  update: (id, data, token) => _req('PUT', '/${name}/' + id, data, token),`,
        `  remove: (id, token) => _req('DELETE', '/${name}/' + id, null, token),`,
        `};`,
        ``
      );
    });
  }

  if (wsEnabled) {
    lines.push(
      `// --- WebSocket (requires socket.io-client) ---`,
      `// import { io } from 'socket.io-client';`,
      `// const socket = io('${baseUrl}');`,
      `// socket.on('webhook:received', (data) => console.log(data));`,
      ``
    );
  }

  // Export block
  const exports = [];
  if (features.auth?.enabled) exports.push('skeletalAuth');
  if (features.otp?.enabled) exports.push('skeletalOTP');
  if (features.webhooks?.enabled) exports.push('skeletalWebhooks');
  (features.crud?.models || []).forEach(m => {
    exports.push(`skeletal${m.name.charAt(0).toUpperCase() + m.name.slice(1)}`);
  });

  lines.push(
    `// Export`,
    `if (typeof module !== 'undefined') {`,
    `  module.exports = { ${exports.join(', ')} };`,
    `}`
  );

  const code = lines.join('\n');
  const target = outputPath || path.resolve(process.cwd(), 'skeletal-client.js');
  fs.writeFileSync(target, code, 'utf8');
  return target;
}

module.exports = { generateSDK };
